// <auto-generated />
using System;
using BloggingAppAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BloggingAppAPI.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20191024095439_UpdatedBlogTable")]
    partial class UpdatedBlogTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BloggingAppAPI.Model.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlogAuthor")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("BlogBrief")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<DateTime>("BlogDateTimeStamp");

                    b.Property<string>("BlogHeading")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("BlogMainImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
